name: allele_muts
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipympl
  - ipython
  - mamba
  - matplotlib
  - numba
  - pandas
  - pyaml
  - pycodestyle
  - python=3.9
  - ruamel_yaml
  - numpy
  - pip
  - pip:
      - tbparse  
prefix:
